name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  collect:
    name: Collect sysconfig
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Generate sysconfig.json
        run: |
          python3 generate_sysconfig.py
          cat sysconfig-*.json
      - name: Create Pull Request
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' }}
        uses: peter-evans/create-pull-request@v4
        with:
          delete-branch: true
          add-paths: |
            sysconfig-*.json
          title: 'Update sysconfig for macOS'
          commit-message: 'Update sysconfig for macOS'
